113 make the applicants overview more visually appealing
appKom/online-opptak pull request #114
Opened 2024-07-02 09:54 UTC by fredrir

2024-07-13 13:50 UTC, julian-ao commented
Får 400 bad request når jeg prøver å sende inn søknad?

{"error":"Invalid data format"}

2024-07-13 13:57 UTC, fredrir commented
> Får 400 bad request når jeg prøver å sende inn søknad?
> 
> 
> 
> {"error":"Invalid data format"}
> 
> 
> 
> 
> 
> Virker ikke som at du har gjort noe i denne PRen da.
> 
> 
> 
> Får det når jeg sender inn søknad på "qwertyu"-perioden

Tror problemet skal være fikset i branch 111🙌

2024-07-13 14:04 UTC, julian-ao commented
> > Får 400 bad request når jeg prøver å sende inn søknad?
> > {"error":"Invalid data format"}
> > Virker ikke som at du har gjort noe i denne PRen da.
> > Får det når jeg sender inn søknad på "qwertyu"-perioden
> 
> Tror problemet skal være fikset i branch 111🙌

Er det en PR på den?

2024-07-14 11:40 UTC, julian-ao requested changes

2024-07-14 11:40 UTC, julian-ao commented on components/applicantoverview/ApplicantCard.tsx
> +                <br />
i think we should use styling to change the spacing and not br's?

2024-07-14 11:40 UTC, julian-ao commented on components/applicantoverview/ApplicantCard.tsx
> +        <br />
same here?

2024-07-14 19:53 UTC, julian-ao approved these changes

2024-07-15 18:12 UTC, merged