New component PageTitle
appKom/online-opptak pull request #174
Opened 2024-07-21 20:52 UTC by julian-ao

![image](https://github.com/user-attachments/assets/cd62457f-605b-476a-871e-9e9bfe5ef3cc)

![image](https://github.com/user-attachments/assets/466fc062-5013-42ae-95ec-385e11b223e1)

![image](https://github.com/user-attachments/assets/6b8ba963-873c-4c3f-98ed-71b0b6fed845)

![image](https://github.com/user-attachments/assets/081f89b6-58ef-45a4-bb26-bd09b34ab86f)

2024-07-21 21:21 UTC, fredrir requested changes

2024-07-22 06:34 UTC, julian-ao commented on pages/committee/[period-id]/[committee]/index.tsx
> +      <PageTitle mainTitle={period?.name || ""} boldMainTitle="Opptaksperiode" subTitle={changeDisplayName(committee)} boldSubTitle="Komité" />
Tenker det ihvertfall er greit at det står "Komité:". Hvis vi passer på at alle periodenavnene blir beskrivende nok, kan vi fjerne "Opptaksperiode:"

2024-07-22 06:36 UTC, julian-ao commented on components/PageTitle.tsx
> +    <div className="w-10/12">
Tanken var egt at dette trengs i de færreste tilfeller. Men kan godt legge det til hvis man har flere komiteer, eller flere nåværende opptaksperioder.

2024-07-22 18:31 UTC, fredrir approved these changes

2024-07-22 18:58 UTC, merged