reduced loading times for applications
appKom/online-opptak pull request #175
Opened 2024-07-21 21:21 UTC by fredrir

2024-07-22 19:15 UTC, julian-ao commented on pages/application/[period-id].tsx
> +
hvordan reduserer dette loading tiden

2024-07-22 19:40 UTC, fredrir commented on pages/application/[period-id].tsx
> +
Fetcher period og application samtidig istedenfor etter hverandre

2024-07-22 20:29 UTC, julian-ao approved these changes

2024-07-23 18:09 UTC, julian-ao requested changes
denne kommer til å ha konflikter med tanstack PRen

2024-07-23 18:11 UTC, fredrir commented
> denne kommer til å ha konflikter med tanstack PRen

Kan egt bare lukke den

2024-07-23 18:11 UTC, closed without merging