Meetings from DB is fetched, matched and sent to DB
appKom/online-opptak pull request #190
Opened 2024-07-24 13:30 UTC by fredrir

2024-07-29 07:13 UTC, julian-ao commented
@jorgengaldal

2024-08-13 12:55 UTC, julian-ao commented
@jorgengaldal

2024-08-14 12:15 UTC, jorgengaldal approved these changes
Skal være good nå.

2024-08-14 12:19 UTC, jorgengaldal requested changes
Tror det bare er den tidssjekken som må endres, ellers ser det good ut.

2024-08-14 12:19 UTC, jorgengaldal commented on algorithm/bridge/fetch_applicants_and_committees.py
> +        if  (application_end > now and period["hasSentInterviewTimes"] == False and interview_end < now) or period["name"] == "FAKE TEST OPPTAK!":
```suggestion
        if  (application_end < now and period["hasSentInterviewTimes"] == False and interview_end > now) or period["name"] == "FAKE TEST OPPTAK!":
```

2024-08-14 14:54 UTC, merged