Add country code selection for application form
appKom/online-opptak pull request #282
Opened 2024-08-18 12:41 UTC by fredrir

2024-08-18 20:39 UTC, julian-ao commented
🤔

![image](https://github.com/user-attachments/assets/6ff01a55-2e70-424b-bca7-0b2925c2f2d3)

2024-08-18 20:59 UTC, julian-ao commented
Fiksa darkmode styling, men usikker på hvordan man styler dropdownen:

![Uploading image.png…]()

2024-08-18 21:03 UTC, julian-ao commented on components/form/SelectInput.tsx
> +          className="absolute z-9 px-1 text-xs text-gray-500 transition bg-white -top-2 left-2 dark:text-gray-200 dark:bg-gray-900"
`z-9` finnes ikke i tailwind. det er som å ikke definere z-indeksen

2024-08-18 21:04 UTC, julian-ao requested changes
husker ikke helt hvorfor z-indeks var satt til 10 på select og textarea, men burde ihvertfall ikke stå z-9

2024-08-19 12:15 UTC, fredrir commented
> Fiksa darkmode styling, men usikker på hvordan man styler dropdownen:
> 
> ![image](https://private-user-images.githubusercontent.com/42567826/358935777-1aca20bd-862b-40b4-91dd-2d4000656052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjcxOTAsIm5iZiI6MTcyNDA2Njg5MCwicGF0aCI6Ii80MjU2NzgyNi8zNTg5MzU3NzctMWFjYTIwYmQtODYyYi00MGI0LTkxZGQtMmQ0MDAwNjU2MDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDExMjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZDc1MGQwMmRjNTQ5M2ZlMzQ4NjY1NmU0NzNjZDIzODM3YjMzZWViODNmNDgxODNmN2JhZDdmZTY5NTAxYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AO0ESMixFrrRo87tBFZ2p2lPnRWlIMpA3Btn0GgYvVM)

Fikk til å sette bakgrunnsfarge på drop down menyen, men ikke ved hover:
![image](https://github.com/user-attachments/assets/52a4dc59-cab5-43b4-af71-b33ddb96214c)

2024-08-20 13:49 UTC, julian-ao approved these changes
Kan merges nå, men da må du inn i databasen og legge til +47 på alle som har søkt allerede

2024-08-21 11:34 UTC, merged